spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_management
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      indent_output: true

server:
  port: 8080